apiVersion: apps/v1
kind: Deployment
metadata:
  name: bison-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bison
  template:
    metadata:
      labels:
        app: bison
    spec:
      containers:
        - name: bison
          image: us-central1-docker.pkg.dev/${GKE_PROJECT}/week3/micro:test
          ports:
            - containerPort: 80
          command: ["sh", "-c", "echo 'Welcome to Bison!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
