apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: my-app
    version: blue  # verander dit voor de pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
