apiVersion: v1
kind: Service
metadata:
  name: app-blue-service
spec:
  selector:
    app: my-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer