name: CI/CD for Blue-Green Deployment

on:
  push:
    branches:
      - main  # Blue deployment
      - test  # Green deployment

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1
  GAR_ZONE: us-central1
  GAR_REPO: my-repo
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Step 3: Configure Docker Authentication
    - name: Docker Authentication
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_ZONE-docker.pkg.dev

    # Step 4: Set up GKE Cluster Credentials
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: autopilot-cluster-1
        location: $GKE_ZONE

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=$GITHUB_SHA
        docker build -t "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:$IMAGE_TAG" .
        docker push "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:$IMAGE_TAG"

    # Step 6: Deploy Blue or Green Environment
    - name: Deploy Application
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          kubectl apply -f k8s/deployment-blue.yaml
          kubectl apply -f k8s/service.yaml
        elif [[ "${{ github.ref_name }}" == "test" ]]; then
          kubectl apply -f k8s/deployment-green.yaml
          kubectl apply -f k8s/service.yaml
        fi

    # Optional: Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl get deployments
        kubectl get services
